version: '3'

services:
    server:
        build:
            context: .
            dockerfile: server.Dockerfile
        volumes:
            - ./data:/opt/data
        ports:
            - "8080:8080"

    builder:
        build:
            context: .
            dockerfile: build.Dockerfile
        volumes:
            - ./target:/tmp/target
